
env: 
  - GO111MODULE=on
  - GOPROXY=https://goproxy.io

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./modzy


archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

project_name: modzy-cli

brews:
  - homepage: 'https://github.com/modzy/homebrew-tap'
    description: 'Repository of Modzy Util taps'
    folder: Formula
    commit_author:
      name: vargasraymondj
      email: vargasraymondj@gmail.com
    tap:
      owner: n8mellis
      name: homebrew-tap